name: Build MiColor Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Original Code
      uses: actions/checkout@v4
      with:
        repository: lanweikayu/HyperOS_color-eyecare_fix
        ref: main
        path: src_repo

    - name: Set up Android NDK r27
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27
        add-to-path: true

    - name: Build with ndk-build
      run: |
        echo "查看目录结构:"
        ls -la src_repo/
        echo "进入hal目录:"
        cd src_repo/hal
        echo "开始编译:"
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk NDK_APPLICATION_MK=Application.mk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: micolor-service
        path: |
          src_repo/hal/libs/arm64-v8a/vendor.xiaomi.hardware.displayfeature_aidl-service
          src_repo/hal/vendor.xiaomi.hardware.displayfeature_aidl-service.rc
          src_repo/hal/vendor.xiaomi.hardware.displayfeature_aidl-service.xml
